### ISSUE TITLE
Creating Subs

### ISSUE THREAD

**Issue by eskimos25** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#11]
Hi, I've found that with some courses the subtitles doesn't generate. I've created a list of them for you to check it out:

- LINQ Fundamentals
- Entity Framework Core 2 - Getting Started
- AngularJS Services In-depth
- AngularJS In-Depth
- An AngularJS Playbook
- Using Git for Source Control in Visual Studio 2019
- Specification Pattern in C#
- Angular Architecture and Best Practices
- C# Extension Methods
- Getting Started with Asynchronous Programming in .NET
- C# Fundamentals

Thanks in advance!

**Comment by mrvogiacu** [comment]
Hello @eskimos25,

I try with the course "LINQ Fundamentals" and I see the subtitle was created.

https://imgur.com/xvkA66D
https://imgur.com/wjQh4sw

**Comment by eskimos25** [comment]
Hello @mrvogiacu! and thanks for the quick reply... look, i've downloaded again the "LINQ Fundamentals" course and decrypted it **without** subtitles. This was with the compiled application. Strange thing is that I've downloaded the source, and while debbuging, **subtitles are generating perfectly**. I think it might be because of the locale of my operating system (es-AR). Unfortunately I don't have much time to keep checking the code. I'm going to try changing the locale to en-US and keep you in touch.

**Comment by mrvogiacu** [comment]
So can I close this issue?

**Comment by eskimos25** [comment]
I close it for you. Thanks!
