### ISSUE TITLE
Where I can find the .db file?

### ISSUE THREAD

**Issue by zohozer** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#13]
I just run this software using Wine emulator on my MacBookPro with MacOS 10.14.

The GUI version it is asking me to locate a .DB file which I don't know from where to take.

Where I can find the .DB file requested?

**Comment by mrvogiacu** [comment]
If you don't change anything, the DB file location is the same with Pluralsight Offline Player

**Comment by zohozer** [comment]
I'm using the MacOS version of PluralSight player. I do found a .db file called "Cache.db" located into "/Users/username/Library/Caches/com.pluralsight.pluralsight-mac"

**Comment by mrvogiacu** [comment]
I'm not sure my tool work with pluralsight Mac version. Can you try it and tell me about result?

**Comment by mrvogiacu** [comment]
Long time and no answer. I will close this issue
