### ISSUE TITLE
recognize course

### ISSUE THREAD

**Issue by amir-safetymatch** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#14]
If you move course files, it can't recognize them...
but if you do not that it's ok and works well

**Comment by mrvogiacu** [comment]
Please change the Course Path to your course location

https://imgur.com/TqQlJVh

**Comment by amir-safetymatch** [comment]
I know my friend :)
I don't know why but the course should be added in original Pluralsight offline player so your program recognizes the course...
https://imgur.com/Cdcb2E9

**Comment by mrvogiacu** [comment]
I don't understand what you mean. But If you move the course and delete them from POP, the tool can't recognize them, because the tool need The courses existed in POP db to mapping clips with PVS file.
