### ISSUE TITLE
Decryption broken

### ISSUE THREAD

**Issue by atcole4** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#15]
Looks like decryption isn't working any longer. Videos are being decoded as file "0" and are in unplayable format

**Comment by mrvogiacu** [comment]
Are you try with latest version?

**Comment by atcole4** [comment]
Yes with both the latest push and the previous version ~ 15 days ago

**Comment by mrvogiacu** [comment]
Can you give me the course name?

**Comment by atcole4** [comment]
Sure, Getting Started with NLP Deep Learning Using PyTorch and fastai

**Comment by atcole4** [comment]
![image](https://user-images.githubusercontent.com/25810948/79674317-fea97600-81af-11ea-9ca4-44d046d4e14b.png)

**Comment by mrvogiacu** [comment]
![image](https://user-images.githubusercontent.com/14990781/79674382-dd2aa780-820c-11ea-877b-4a87e231b7c6.png)

Everything works perfectly for me. Did you remove the course from POP before decrypt?

**Comment by atcole4** [comment]
Nope didn't remove anything - What version of the Offline player client do you have?

**Comment by atcole4** [comment]
Oh that is odd.. It works using the GUI -- I was using the separate decryption project with CLI. I'll dig in the source and figure out what I'm doing wrong.. 

Thanks for your follow up :)
