### ISSUE TITLE
The Pluralsight encryption has been changed

### ISSUE THREAD

**Issue by m-elarousy** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#16]
The Pluralsight encryption has been changed

**Comment by mrvogiacu** [comment]
What is the POP version are you using?
The latest tool version (1.5) is working with the latest POP version (1.0.247).

**Comment by alxizr** [comment]
Hi, 
First of all thanks for the tool! really appreciate it. 
Any chance to change the decryption process to be threaded as in parallel to the number of courses to run and not cascading it. ?? 
I am not a .net developer but as like in other languages that support threading you will only need to create a thread and pass the decryption method as target argument. this way we can shorten the time we wait for the decryption to finish by factor of N. 
thanks

**Comment by mrvogiacu** [comment]
> Hi,
> First of all thanks for the tool! really appreciate it.
> Any chance to change the decryption process to be threaded as in parallel to the number of courses to run and not cascading it. ??
> I am not a .net developer but as like in other languages that support threading you will only need to create a thread and pass the decryption method as target argument. this way we can shorten the time we wait for the decryption to finish by factor of N.
> thanks

Hello friend,

The answer is yes, .NET has some method to help the decrypt process run with parallel to make it faster. But I think with the reason is decrypt to storage and watch later, It not necessary.

**Comment by m-elarousy** [comment]
> What is the POP version are you using?
> The latest tool version (1.5) is working with the latest POP version (1.0.247).

it's working fine now , thanks a lot
