### ISSUE TITLE
Read course doesn't word for the first time

### ISSUE THREAD

**Issue by ahlanebik** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#17]
Hi,
I download some courses from the Pluralsight's application offline ... and when i make (Read Course) nothing happened and the course doesn't appear until i drop it and reload it for the second time 
At this time it works.
I 've made more than 3 tries before writing to you 
I don't know if it's a bug or something else

Thanks for your help !

**Comment by mrvogiacu** [comment]
> until I drop it and reload it for the second time
You mean is press the Read Course button the second time

**Comment by ahlanebik** [comment]
Thank.s for replying me,
I've just do 3 courses after writing to you ... so i had to delete the course and downnload it  (twice all the time) if i want to show it (to be displayed) and after i can select it to run 

PS :  There is nothing happened in the first time , so no message except this in the black screen (on the right of the soft) : 
Database connection opened.
Getting course data . . .
Complete!

**Comment by mrvogiacu** [comment]
The log is mean the course list is read success, but for some reason, the UI doesn't update. I will check it

**Comment by ahlanebik** [comment]
It looks crazy to understand ... I've dropped the folder that contains the .psv manually, and from the player of Pluralsight , and also from your soft .... without success. I start your soft and let it open when i download, i start it after download .... so i 've made a different combination of possibilities ....The only solution i find it is to download the course, try to read it (no result) I drop the course and download it again, at this time all's well
PS: till now, I have download 14 courses but I've used 28 downloads
Sincerely i'm not able to understand what really happened

**Comment by ahlanebik** [comment]
Thank S

Can i send you a small video ?  and it will be better to understand what i mean ....

**Comment by mrvogiacu** [comment]
> Thank S
> 
> Can i send you a small video ? and it will be better to understand what i mean ....

Yes, please :D

**Comment by ahlanebik** [comment]
your email please, i didn't find where i can do that here

**Comment by mrvogiacu** [comment]
> your email please, i didn't find where i can do that here

my email: mr.vogiacu@gmail.com

**Comment by ahlanebik** [comment]
Thanks , i will prepare that in a moment

**Comment by mrvogiacu** [comment]
> Thanks , i will prepare that in a moment

What is the version are you using? GUI or command

**Comment by ahlanebik** [comment]
V 1.5 

i ve just send U the videos i hope not disturbing u a lot 
sorry for leting U waiting (i have somme trouble with this machine ) in this moment 
PS : i used the website : wetranfer.com to send the file

**Comment by mrvogiacu** [comment]
I'm dowoading your video 😊

**Comment by ahlanebik** [comment]
tell me please,  your soft was developed by witch language (c# or Python ...)

**Comment by mrvogiacu** [comment]
> tell me please, your soft was developed by witch language (c# or Python ...)

My tool developed by .NET. I will prepare a version with a written log function to check what happens when reading the course.

**Comment by ahlanebik** [comment]
thanks a lot .... do u have an idea now for what i was saying before 
it looks very strange!

**Comment by ahlanebik** [comment]
i will continue to download twice any course untill we understand what is the prob ...
Thank u for replying me quickly And hope to read u soon

**Comment by mrvogiacu** [comment]
https://www.mediafire.com/file/au7iyi64thi68ud/Release.zip/file

> i will continue to download twice any course untill we understand what is the prob ...
> Thank u for replying me quickly And hope to read u soon

https://www.mediafire.com/file/au7iyi64thi68ud/Release.zip/file
Please try this version, download 1 course as the first time. read the course, send me the log file and the DB file (pluralsight.db)

**Comment by ahlanebik** [comment]
Hi again,
i ll send u the files but i have to tell you that the same thing done with this version, i download  twice ... what i have to do is to try this in the others computers .. question of being sur that is not prob cominf from my system .
there are 2 files as you claim ..
[pluralsight .zip](https://github.com/mrvogiacu/Decrypt-PluralSight-Videos-GUI/files/4502083/pluralsight.zip)
[2020-04-20.zip](https://github.com/mrvogiacu/Decrypt-PluralSight-Videos-GUI/files/4502084/2020-04-20.zip)

**Comment by mrvogiacu** [comment]
> Hi again,
> i ll send u the files but i have to tell you that the same thing done with this version, i download twice ... what i have to do is to try this in the others computers .. question of being sur that is not prob cominf from my system .
> there are 2 files as you claim ..
> [pluralsight .zip](https://github.com/mrvogiacu/Decrypt-PluralSight-Videos-GUI/files/4502083/pluralsight.zip)
> [2020-04-20.zip](https://github.com/mrvogiacu/Decrypt-PluralSight-Videos-GUI/files/4502084/2020-04-20.zip)

I don't know why, but my tool detects your course isn't download completed, so it doesn't display them. You can try to follow step bellow to check the problem come from my tool or POP:
+ for testing, you just download small course
+ close POP, and reopen it. Check for course continues to download or display as completed.

I will find ways to change the function which checks the course has completed.

**Comment by mrvogiacu** [comment]
> Hi again,
> i ll send u the files but i have to tell you that the same thing done with this version, i download twice ... what i have to do is to try this in the others computers .. question of being sur that is not prob cominf from my system .
> there are 2 files as you claim ..
> [pluralsight .zip](https://github.com/mrvogiacu/Decrypt-PluralSight-Videos-GUI/files/4502083/pluralsight.zip)
> [2020-04-20.zip](https://github.com/mrvogiacu/Decrypt-PluralSight-Videos-GUI/files/4502084/2020-04-20.zip)

Can you try this version and tell me the result. if the bug still appears, please send me the log again
https://www.mediafire.com/file/o3drcswtmpwegyq/Release.zip/file

**Comment by ahlanebik** [comment]
Hi, It works well 
I use your tool in my Laptop... all's wok fine 
To be sure  and eliminate any confusion that i have something wrong in the first Desktop, as soon as i have a few minutes i will do the same in the other desktop or another PC .... It appears good now, Thank U a lot for your help !

Is there any guide or help for your tool somewhere

**Comment by mrvogiacu** [comment]
For now the tool don't have any guide. It have only about window. You can press F1 to see it

**Comment by ahlanebik** [comment]
Hi again, once i make all the tests I give you all the results ... 
I have a question about some videos of  some channel TV , i take the habits to download hem with a tool captvty  but now it seems that the videos are proected by DRM method so can you tell me if it s possible to have them
Wainting for your answer (if yes) i'll give you the link to check

Thanks again

**Comment by mrvogiacu** [comment]
> Hi again, once i make all the tests I give you all the results ...
> I have a question about some videos of some channel TV , i take the habits to download hem with a tool captvty but now it seems that the videos are proected by DRM method so can you tell me if it s possible to have them
> Wainting for your answer (if yes) i'll give you the link to check
> 
> Thanks again

- For testing, please use the latest version I just updated.
- For DRM protect, I have never research about it, you can google, I think you will get the answer.

**Comment by ahlanebik** [comment]
Ok .. I'll do it soon!

**Comment by ahlanebik** [comment]
Great, it works well
I tried with 4 courses, very nice this last version

**Comment by mrvogiacu** [comment]
Glad to hear it, so I will close this issue

**Comment by ahlanebik** [comment]
Can I have the idea of what was wrong before!

**Comment by mrvogiacu** [comment]
Yes, I'm not sure where is the problem come from, but my tool detect the course  isn't download complete, so it don't show any course.
