### ISSUE TITLE
exe file in DecryptPluralSightVideosGUI

### ISSUE THREAD

**Issue by degr8sid-code** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#21]
There is no .exe file in DecryptPluralSightVideosGUI folder.

**Comment by mrvogiacu** [comment]
> There is no .exe file in DecryptPluralSightVideosGUI folder.

Are you download source code for looking for execution files?

Please download the file [here](https://github.com/mrvogiacu/Decrypt-PluralSight-Videos-GUI/releases/latest).
