### ISSUE TITLE
Clean database

### ISSUE THREAD

**Issue by patoomartinez** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#23]
Hi! how can i clean the database files? everytime i download a new course, it shows xxxx clips.
Thanks!

**Comment by mrvogiacu** [comment]
I don't understand what you mean. If you want delete course after decrypt, you can check the Delete checkbox. If you want delete all course only, you can uncheck decrypt, create sub and check Delete checkbox only, and click run, the tool will delete all course selected from database
