### ISSUE TITLE
Read Course Give 0 courses

### ISSUE THREAD

**Issue by saulpalv** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#24]
Im getting no courses, im not new to this app, just a new device, did clean install.

```
Database connection opened.
Getting course data . . .
Complete! Total: 0 courses
```
db on default folder `...AppData\Local\Pluralsight\pluralsight.d`b
course path is on external drive `G:\PS`
Pluralsight offline player Version 1.0.247.0

i verified course path matches on pluralsight oflline  player and verified .db location too

**Comment by mrvogiacu** [comment]
Can you give me the screenshot of the tool when you already configuration, and the screenshot of `G:\PS` folder content

**Comment by saulpalv** [comment]
![1](https://user-images.githubusercontent.com/19735362/79939725-13d70c80-841d-11ea-84db-7655241a8e57.png)
![2](https://user-images.githubusercontent.com/19735362/79939724-12a5df80-841d-11ea-9320-9ef6a641b076.png)
![3](https://user-images.githubusercontent.com/19735362/79939726-13d70c80-841d-11ea-993a-0384e01c5beb.png)
![4](https://user-images.githubusercontent.com/19735362/79939727-13d70c80-841d-11ea-8c60-e7824c307308.png)

**Comment by mrvogiacu** [comment]
please change the Course path to `G:\PS\course`

**Comment by saulpalv** [comment]
> please change the Course path to `G:\PS\course` and try again

doesn't work, i also tried with version 1.3, but no luck

**Comment by saulpalv** [comment]
> please change the Course path to `G:\PS\courses` and try again

it works, thanks

**Comment by mrvogiacu** [comment]
> > please change the Course path to `G:\PS\courses` and try again
> 
> it works, thanks

You are welcome :D
