### ISSUE TITLE
Decrypted files are not playable since 4/10/2020

### ISSUE THREAD

**Issue by schuchuva** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#26]
Seems like they changed encryption method recently. All decrypted files are not playable. It started around 4/10/2020.

**Comment by mrvogiacu** [comment]
Hello @schuchuva,

Please download latest version [here](https://github.com/mrvogiacu/Decrypt-PluralSight-Videos-GUI/releases/latest) and try agian. It work with latest POP version (1.0.247)

**Comment by schuchuva** [comment]
Thanks - works with latest version.
