### ISSUE TITLE
Fix newPath assignment in DecryptAllVideos

### ISSUE THREAD

**Issue by aLLaNoN81** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#27]
File "Decryptor.cs", method "DecryptAllVideos"
Please fix "newPath" assigement with: Path.Combine(outputPath, (clip.ClipIndex < 10 ? "0" : "") + (clip.ClipIndex) + ". " + clip.ClipTitle + ".mp4");

Otherwise file name will always be "0"

**Comment by mrvogiacu** [comment]
Hello @aLLaNoN81 

That is old code with the Commandline version. I don't develop it anymore. Please Using GUI version
