### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by wildhevire** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#28]
![image](https://user-images.githubusercontent.com/9078000/80300045-7a647d80-87c3-11ea-83a3-3dbdd3240488.png)
I dont really know what happen so i cant give any detail, but this what i got

**Comment by mrvogiacu** [comment]
Can you give me the log file?

**Comment by wildhevire** [comment]
[2020-04-26.txt](https://github.com/mrvogiacu/Decrypt-PluralSight-Videos-GUI/files/4534879/2020-04-26.txt)

**Comment by wildhevire** [comment]
I hope u could fix this soon, my internet just about run out but i still have some course to download

**Comment by mrvogiacu** [comment]
I already know where is the problem. Maybe I will release the fixed version at tonight

**Comment by wildhevire** [comment]
I also found a way to do some temporary fix.
Replace the image (corrupted) in course folder by another image that not corrupted
Btw i will close this issue, thx for help

**Comment by mrvogiacu** [comment]
Hello @wildhevire,

When you get this error again, can you archive the image file of the error course and send it to me?

**Comment by wildhevire** [comment]
I think i cant, i already replaced all of them and delete while decrypted, sorry

**Comment by wildhevire** [comment]
But if i found it again later, i will sent it here

**Comment by mrvogiacu** [comment]
Hello @wildhevire,

I already fix this issue, you can download latest version (1.7) and try again 😊.
