### ISSUE TITLE
Decrypted files are unplayable

### ISSUE THREAD

**Issue by tester16430** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#8]
Something has changed in the content , files after decryption are unplayable

**Comment by mrvogiacu** [comment]
Hello friend. If you using pluralsight offline player to download, please make sure this tool can play the error video, because sometime the offical tool can't download the video. It just create a file with zero byte. I got this case before

**Comment by dragonofdragons** [comment]
> Hello friend. If you using pluralsight offline player to download, please make sure this tool can play the error video, because sometime the offical tool can't download the video. It just create a file with zero byte. I got this case before

for me also same problem. the decrypted files are not playable

**Comment by tester16430** [comment]
Hello 
Offline player plays fine - checked. I downloaded new files and when checked individual mp4 with MediaInfo - it can't recognize as media file. I compared 2 identical files (one pluralsight course downloaded some time ago and for comparison the same course downloaded today) - files have identical size but contents are different.

**Comment by mrvogiacu** [comment]
@tester16430 can you give me the name of the course which has the error clip

**Comment by tester16430** [comment]
No problem, You may check https://app.pluralsight.com/library/courses/c-sharp-design-patterns-adapter but also noticed this problem on many other materials like conferences ( https://app.pluralsight.com/library/courses/that-conference-2019-session-50 )

**Comment by dragonofdragons** [comment]
> No problem, You may check 'C# Design Patterns: Adapter' but also noticed this problem on many other materials like conferences ( 'THAT Conference '19: UI Development in a Microservices World' )

i tried in two courses one is rust fundamentals and other is automating aws operations with the aws cli. both are not playing

**Comment by dragonofdragons** [comment]
![Uploading 15866211257313548606777600718064.jpg…]()
getting this error

**Comment by kataki** [comment]
i had the same issue it looks like the new pluralsight update is the reason they changed something in the encryption probably if u check inside pluralsight folder (C:\Users\xxxx\AppData\Local\Pluralsight) u will find folders with the updated app like:
app-1.0.242
app-1.0.246
app-1.0.247
the issue started with version "app-1.0.247" 
I was able to make it work again by deleting the folder "app-1.0.247"and the courses downloaded inside "courses" folder and the database "pluralsight.db" (deleting the courses and db file will delete all the downloaded courses and reset the app)
and then you can download the new courses again it should work fine as long as it doesn't update to 1.0.247

**Comment by tester16430** [comment]
> 
> 
> i had the same issue it looks like the new pluralsight update is the reason they changed something in the encryption probably if u check inside pluralsight folder (C:\Users\xxxx\AppData\Local\Pluralsight) u will find folders with the updated app like:
> app-1.0.242
> app-1.0.246
> app-1.0.247
> the issue started with version "app-1.0.247"
> I was able to make it work again by deleting the folder "app-1.0.247"and the courses downloaded inside "courses" folder and the database "pluralsight.db" (deleting the courses and db file will delete all the downloaded courses and reset the app)
> and then you can download the new courses again it should work fine as long as it doesn't update to 1.0.247

I uninstalled the pluralsight app during testing the problem. I don't have previous versions, only "app-1.0.247". It it possible to get from you this older one ?

**Comment by kataki** [comment]
> > i had the same issue it looks like the new pluralsight update is the reason they changed something in the encryption probably if u check inside pluralsight folder (C:\Users\xxxx\AppData\Local\Pluralsight) u will find folders with the updated app like:
> > app-1.0.242
> > app-1.0.246
> > app-1.0.247
> > the issue started with version "app-1.0.247"
> > I was able to make it work again by deleting the folder "app-1.0.247"and the courses downloaded inside "courses" folder and the database "pluralsight.db" (deleting the courses and db file will delete all the downloaded courses and reset the app)
> > and then you can download the new courses again it should work fine as long as it doesn't update to 1.0.247
> 
> I uninstalled the pluralsight app during testing the problem. I don't have previous versions, only "app-1.0.247". It it possible to get from you this older one ?

https://drive.google.com/uc?id=1iNJHTIqPthEHTuZ5fwoKLW4j4NNXXWZA&export=download

**Comment by sitiom** [comment]
Should be fixed now at #7 .

**Comment by dragonofdragons** [comment]
> > > i had the same issue it looks like the new pluralsight update is the reason they changed something in the encryption probably if u check inside pluralsight folder (C:\Users\xxxx\AppData\Local\Pluralsight) u will find folders with the updated app like:
> > > app-1.0.242
> > > app-1.0.246
> > > app-1.0.247
> > > the issue started with version "app-1.0.247"
> > > I was able to make it work again by deleting the folder "app-1.0.247"and the courses downloaded inside "courses" folder and the database "pluralsight.db" (deleting the courses and db file will delete all the downloaded courses and reset the app)
> > > and then you can download the new courses again it should work fine as long as it doesn't update to 1.0.247
> > 
> > 
> > I uninstalled the pluralsight app during testing the problem. I don't have previous versions, only "app-1.0.247". It it possible to get from you this older one ?
> 
> https://drive.google.com/uc?id=1iNJHTIqPthEHTuZ5fwoKLW4j4NNXXWZA&export=download

the app is auto updating

**Comment by mrvogiacu** [comment]
@sitiom are you tested? Because I try same thge solution with you, but It's not work

**Comment by sitiom** [comment]
Tested two new courses, two old courses. Works to both

**Comment by sitiom** [comment]
Give me a test case

**Comment by mrvogiacu** [comment]
@sitiom I see the DecryptBuffer method of you different with my method. Can you tell me the name of tool you use to decompiler.
PS: I tested and you code is worked. I will build the update soon

**Comment by sitiom** [comment]
Used .net reflector
